/*Insert buildings*/
INSERT INTO buildings (name, address, thumbnail_image_url, main_image_url, amenities, resident_types, building_type, room_types, minimum_cost) VALUES ('White Hall', '21 Forsyth Street', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WHITE-exterior-02-e1511889474120.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WHITE-exterior-02-e1511889474120.jpg', "Laundry, Proctor, Vending Machines, Elevator, Kitchen, Lounge", "First Year", "Economy, Standard", "Traditional", 3425);
INSERT INTO buildings (name, address, thumbnail_image_url, main_image_url, amenities, resident_types, building_type, room_types, minimum_cost) VALUES ('Stetson West', '10 Forsyth Street, Boston MA 02115', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/STW-exterior-Speare-Quad-03-e1511889294218.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/STW-exterior-Speare-Quad-03-e1511889294218.jpg', "Laundry, Proctor, Vending Machines, Elevator, Kitchen, Lounge", "First Year", "Economy, Standard", "Traditional", 3425);
INSERT INTO buildings (name, address, thumbnail_image_url, main_image_url, amenities, resident_types, building_type, room_types, minimum_cost) VALUES ('Stetson East', '11 Speare Place, Boston MA 02115', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/STW-exterior-Speare-Quad-03-e1511889294218.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/STW-exterior-Speare-Quad-03-e1511889294218.jpg', "Laundry, Proctor, Vending Machines, Elevator, Kitchen, Lounge", "First Year", "Economy, Standard", "Traditional", 3425);
INSERT INTO buildings (name, address, thumbnail_image_url, main_image_url, amenities, resident_types, building_type, room_types, minimum_cost) VALUES ('East Village', '291 St. Botolph Street, Boston MA 02115', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/exterior-04.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/exterior-04.jpg', "Laundry, Proctor, Vending Machines, Elevator, Kitchen, Lounge", "First Year", "Enhanced, Standard", "Suite", 3425);

/*Second year buildings*/
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('International Village', '1155 Tremont Street, Boston MA 02115', "Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "First Year, Second Year, Upperclassmen", "Enhanced", "Suite-Style", 5060, 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/INV-exterior-01.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/INV-exterior-01.jpg');
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('West Village A', '500 Parker Street, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "Second Year, Upperclassmen", "Enhanced", "Apartment Style", 6280, 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WVN-exterior-01-e1511888984636.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WVN-exterior-01-e1511888984636.jpg');
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('West Village B', '460 Parker Street, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "Second Year, Upperclassmen", "Enhanced", "Apartment Style", 6280, 'https://www.emporis.com/images/show/434387-Large-exterior-from-west-village-quad.jpg', 'https://www.emporis.com/images/show/434387-Large-exterior-from-west-village-quad.jpg');
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('West Village C', '480 Parker Street, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "Second Year, Upperclassmen", "Enhanced", "Apartment Style", 6280, 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WVC-exterior-01-768x513.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WVC-exterior-01-768x513.jpg');
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('West Village E', '10 Leon Street, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "Second Year, Upperclassmen", "Enhanced", "Apartment Style", 6280, 'https://www.emporis.com/images/show/435585-Large-exterior-from-the-opposite-side-of-ruggles-street.jpg', 'https://www.emporis.com/images/show/435585-Large-exterior-from-the-opposite-side-of-ruggles-street.jpg');
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('West Village F', '40A Leon Street, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "Second Year, Upperclassmen", "Enhanced", "Apartment Style", 6280, 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WVF-common-area-01-1024x684.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WVF-common-area-01-1024x684.jpg');
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('West Village G', '450 Parker Street, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "Second Year, Upperclassmen", "Enhanced", "Apartment Style", 6280, 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/West-G.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/West-G.jpg');
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('West Village H', '440 Parker Street, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "Second Year, Upperclassmen", "Enhanced", "Apartment Style", 6280, 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WVH-exterior-01-768x1150.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/WVH-exterior-01-768x1150.jpg');

INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('Davenport A', '700 Columbus Avenue, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "Second Year, Upperclassmen", "Enhanced", "Apartment Style", 6280, 'https://2ssus4mbuza3wsibg4d4tfzz-wpengine.netdna-ssl.com/wp-content/uploads/2016/02/2-Davenport-Commons-1000x717.jpg', 'https://2ssus4mbuza3wsibg4d4tfzz-wpengine.netdna-ssl.com/wp-content/uploads/2016/02/2-Davenport-Commons-1000x717.jpg');
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('Davenport B', '696 Columbus Avenue, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture, Air Conditioning", "Second Year, Upperclassmen", "Enhanced", "Apartment Style", 6280, 'https://2ssus4mbuza3wsibg4d4tfzz-wpengine.netdna-ssl.com/wp-content/uploads/2016/02/2-Davenport-Commons-1000x717.jpg', 'https://2ssus4mbuza3wsibg4d4tfzz-wpengine.netdna-ssl.com/wp-content/uploads/2016/02/2-Davenport-Commons-1000x717.jpg');

INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('Burstein Hall', '458 Huntington Avenue, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture", "Second Year, Upperclassmen", "Economy, Standard", "Apartment Style", 4460, 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/BUR-exterior-02.jpg', 'https://www.northeastern.edu/housing/wp-content/uploads/2017/05/BUR-exterior-02.jpg');
INSERT INTO buildings (name, address, amenities, resident_types, building_type, room_types, minimum_cost, thumbnail_image_url, main_image_url) VALUES ('Rubenstein Hall', '464 Huntington Avenue, Boston MA 02115', "Kitchen, Laundry, Proctor, Vending Machines, Elevator, Lounge, Furniture", "Second Year, Upperclassmen", "Economy, Standard", "Apartment Style", 4460, 'https://66.media.tumblr.com/b6fcc587617677e5811f41d42344196c/tumblr_o36yxjWhYE1v9q01co1_1280.jpg', 'https://66.media.tumblr.com/b6fcc587617677e5811f41d42344196c/tumblr_o36yxjWhYE1v9q01co1_1280.jpg');



/*Insert users*/
INSERT INTO users (username, password, name, major, year) VALUES ('liu.st@husky.neu.edu', 'password', 'Stanley Liu', 'Computer Science', 3);
INSERT INTO users (username, password, name, major, year) VALUES ('hoi.a@husky.neu.edu', 'password', 'Aryton Hoi', 'Computer Science', 4);

/*Insert staff*/
INSERT INTO staff (username, password, name, role) VALUES ('aoun@husky.neu.edu', 'password', 'Aoun', 'President');

/*Insert review*/
-- INSERT INTO reviews (username, user_username, date, text, image_url, sentiment, building_id) VALUES ('hoi.a@husky.neu.edu', 'hoi.a@husky.neu.edu', '2020-04-14', 'This place is amazing!', 0.8999999761581421, 1);